/*
	File: fn_vehicleWeightCfg.sqf
	Author: Bryan "Tonic" Boardwine
	
	Description:
	Master configuration for vehicle weight.
*/
private["_className"];
_className = [_this,0,"",[""]] call BIS_fnc_param;

switch (_className) do
{
	case "C_Offroad_01_F": {65};
	case "B_G_Offroad_01_F": {65};
	case "B_Quadbike_01_F": {25};
	case "I_Truck_02_covered_F": {250};
	case "I_Truck_02_transport_F": {200};
	case "C_Hatchback_01_F": {40};
	case "C_Hatchback_01_sport_F": {45};
	case "C_SUV_01_F": {50};
	case "C_Van_01_transport_F": {100};
	case "I_G_Van_01_transport_F": {100};
	case "C_Van_01_box_F": {150};
	case "C_Boat_Civil_01_F": {85};
	case "C_Boat_Civil_01_police_F": {85};
	case "C_Boat_Civil_01_rescue_F": {85};
	case "B_Truck_01_box_F": {450};
	case "B_Truck_01_transport_F": {325};
	case "B_MRAP_01_F": {65};
	case "O_MRAP_02_F": {60};
	case "I_MRAP_03_F": {58};
	case "B_Heli_Light_01_F": {90};
	case "O_Heli_Light_02_unarmed_F": {210};
	case "I_Heli_Transport_02_F": {375};
	case "C_Rubberboat": {45};
	case "O_Boat_Armed_01_hmg_F": {175};
	case "B_Boat_Armed_01_minigun_F": {175};
	case "I_Boat_Armed_01_minigun_F": {175};
	case "B_G_Boat_Transport_01_F": {45};
	case "B_Boat_Transport_01_F": {45};
	case "O_Truck_03_transport_F": {285};
	case "O_Truck_03_covered_F": {300};
	case "O_Truck_03_device_F": {350};
	case "Land_CargoBox_V1_F": {5000};
	case "Box_IND_Grenades_F": {350};
	case "B_supplyCrate_F": {700};
	case "DAR_ExplorerPolice":{65};
	case "DAR_ExplorerPoliceStealth":{65};
	case "b_offroad_medic":{65};
	case "b_suv_medic":{65};
	case "b_suv_medic_grey":{65};
	case "DAR_TahoeEMS":{65};
	case "I_Truck_02_medical_F":{65};
	case "O_Truck_03_medical_F":{65};
	case "B_Truck_01_medical_F":{65};
	case "b_heli_medic":{65};
	case "RSPack_1d":{65};
	case "b_orca_medic":{65};
	case "EMD_CH49_Mohawk_FG":{65};
	case "emu_offroad_g1":{65};
	case "Jonzie_96_Impala":{65};
	case "DAR_ImpalaCiv":{65};
	case "DAR_ImpalaCivA":{65};
	case "DAR_TaurusCiv":{65};
	case "DAR_TaurusCivBlue":{65};
	case "DAR_TaurusCivBlack":{65};
	case "DAR_FusionCiv":{65};
	case "DAR_FusionCivBlue":{65};
	case "DAR_FusionCivRed":{65};
	case "DAR_FusionCivBlack":{65};
	case "DAR_TahoeCiv":{65};
	case "DAR_TahoeCivRed":{65};
	case "DAR_TahoeCivBlue":{65};
	case "DAR_TahoeCivSilver":{65};
	case "DAR_ChargerCiv":{65};
	case "DAR_Charger_Blue":{65};
	case "SAL_AudiCiv":{65};
	case "SAL_AudiCivRed":{65};
	case "SAL_AudiCivSilver":{65};
	case "SAL_AudiCivBlack":{65};
	case "DAR_ChallengerCivWhite":{65};
	case "DAR_ChallengerCivRed":{65};
	case "DAR_ChallengerCivBlack":{65};
	case "DAR_ChallengerCivOrange":{65};
	case "emu_offroad_digi1":{65};
	case "emu_offroad_digi_dark":{65};
	case "emu_offroad_digi_dark2":{65};
	case "emu_offroad_t1":{65};
	case "max_robbers_Hatchback":{65};
	case "max_robbers_suv":{65};
	case "EMU_MH9":{65};
	case "EMU_MH9_camo":{65};
	case "EMU_MH9_yel":{65};
	case "max_Police_Quadbike":{65};
	case "demian2435_police_offroad":{65};
	case "DAR_ImpalaPolice":{65};
	case "max_prison_van":{200};
	case "DAR_TaurusPolice":{65};
	case "demian2435_police_car":{65};
	case "DAR_TahoePolice":{65};
	case "Max_Suv_undercover":{65};
	case "DAR_ChargerPolice":{65};
	case "DAR_ImpalaPoliceSlick":{65};
	case "max_Hatchback_undercover":{65};
	case "DAR_TahoePoliceSlick":{65};
	case "DAR_ExplorerPolice":{65};
	case "DAR_TahoePoliceSlick":{65};
	case "DAR_ExplorerPolice":{65};
	case "DAR_TahoePoliceDet":{65};
	case "DAR_CVPISlick":{65};
	case "DAR_ChargerPoliceStateSlick":{65};
	case "demian2435_swat_offroad":{65};
	case "DAR_ImpalaPoliceDet":{65};
	case "Jonzie_96_Impala_Unmarked":{65};
	case "EMU_MH9_des":{65};
	case "EMU_MH9_navy":{65};
	case "EMU_MH9_wh":{65};
	case "EMU_MH9_blk":{65};
	case "Mohawk_civ1_FG":{65};
	case "I_Heli_light_03_unarmed_F":{65};
	case "B_Heli_Transport_01_F":{65};
	case "kyo_MH47E_base":{65};
	case "IVORY_T6A_1":{65};
	default {-1};
};